In [12]:
import geopandas
import pandas as pd

In [ ]:
shapefile = "/Users/bwarren/Downloads/tl_2018_us_cd116/tl_2018_us_cd116.shp"
states = geopandas.read_file(shapefile)

In [19]:
states.head()

,STATEFP,CD116FP,GEOID,NAMELSAD,LSAD,CDSESSN,MTFCC,FUNCSTAT,ALAND,AWATER,INTPTLAT,INTPTLON,geometry
0,27,07,2707,Congressional District 7,C2,116,G5200,N,86580712408,5058381039,+46.5530202,-095.6759048,"POLYGON ((-97.23909 48.96826, -97.23909 48.968..."
1,27,02,2702,Congressional District 2,C2,116,G5200,N,6314464923,243358361,+44.4789680,-092.8530418,"POLYGON ((-93.91131 44.54651, -93.91024 44.548..."
2,27,06,2706,Congressional District 6,C2,116,G5200,N,7460634590,408723230,+45.3368069,-093.8520551,"POLYGON ((-94.64041 45.37072, -94.64039 45.371..."
3,27,08,2708,Congressional District 8,C2,116,G5200,N,72281499178,12448503736,+47.2503370,-092.9638699,"POLYGON ((-95.18322 47.41277, -95.16598 47.412..."
4,17,01,1701,Congressional District 1,C2,116,G5200,N,669256000,2067510,+41.5466708,-087.8357472,"POLYGON ((-88.13677 41.42285, -88.13633 41.422..."

In [22]:
state_fips = pd.read_csv('state_fips.csv')
state_fips.head()

       stname   st  stusps
0     Alabama    1      AL
1      Alaska    2      AK
2     Arizona    4      AZ
3    Arkansas    5      AR
4  California    6      CA

In [47]:
sample = pd.read_csv('~/.interchange/gerrymander_sample.csv')
sample = sample.loc[:, ~sample.columns.str.contains('^Unnamed')]
sample = sample.rename(columns=lambda x: x.strip())
sample.head()

,year,state,district,republican_candidate,republican_votes,republican_party,democratic_candidate,democratic_votes,democratic_party,r_edge
0,2002,Alabama,1,Jo Bonner,108102.0,republican,Judy McCain Belk,67507.0,democrat,40595.0
1,2002,Alabama,2,Terry Everett,129233.0,republican,Charles Woods,55495.0,democrat,73738.0
2,2002,Alabama,3,Mike Rogers,91169.0,republican,Joe Turnham,87351.0,democrat,3818.0
3,2002,Alabama,5,Stephen P. Engel,48226.0,republican,Robert E. (Bud) Cramer Jr.,143029.0,democrat,-94803.0
4,2002,Alaska,0,Don Young,169685.0,republican,Clifford Greene,39357.0,democrat,130328.0

In [48]:
sample = sample.merge(state_fips, left_on='state', right_on='stname')
sample.head()

,year,state,district,republican_candidate,republican_votes,republican_party,democratic_candidate,democratic_votes,democratic_party,r_edge,stname,st,stusps
0,2002,Alabama,1,Jo Bonner,108102.0,republican,Judy McCain Belk,67507.0,democrat,40595.0,Alabama,1,AL
1,2002,Alabama,2,Terry Everett,129233.0,republican,Charles Woods,55495.0,democrat,73738.0,Alabama,1,AL
2,2002,Alabama,3,Mike Rogers,91169.0,republican,Joe Turnham,87351.0,democrat,3818.0,Alabama,1,AL
3,2002,Alabama,5,Stephen P. Engel,48226.0,republican,Robert E. (Bud) Cramer Jr.,143029.0,democrat,-94803.0,Alabama,1,AL
4,2004,Alabama,1,Jo Bonner,161067.0,republican,Judy Belk,93938.0,democrat,67129.0,Alabama,1,AL

In [50]:
sample.columns

Index(['year', 'state', 'district', 'republican_candidate', 'republican_votes',
       'republican_party', 'democratic_candidate', 'democratic_votes',
       'democratic_party', 'r_edge', 'stname', ' st', ' stusps'],
      dtype='object')

In [52]:
sample['DISTRICTID'] = sample.district.apply(lambda x: f'{x:02}')
sample['STATEID'] = sample[' st'].apply(lambda x: f'{x:02}')
sample['GEOID'] = sample['DISTRICTID'] + sample['STATEID']

In [53]:
sample

,year,state,district,republican_candidate,republican_votes,republican_party,democratic_candidate,democratic_votes,democratic_party,r_edge,stname,st,stusps,DISTRICTID,STATEID
0,2002,Alabama,1,Jo Bonner,108102.0,republican,Judy McCain Belk,67507.0,democrat,40595.0,Alabama,1,AL,01,01
1,2002,Alabama,2,Terry Everett,129233.0,republican,Charles Woods,55495.0,democrat,73738.0,Alabama,1,AL,02,01
2,2002,Alabama,3,Mike Rogers,91169.0,republican,Joe Turnham,87351.0,democrat,3818.0,Alabama,1,AL,03,01
3,2002,Alabama,5,Stephen P. Engel,48226.0,republican,Robert E. (Bud) Cramer Jr.,143029.0,democrat,-94803.0,Alabama,1,AL,05,01
4,2004,Alabama,1,Jo Bonner,161067.0,republican,Judy Belk,93938.0,democrat,67129.0,Alabama,1,AL,01,01
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3328,2006,Vermont,0,Martha Rainville,117023.0,republican,Peter Welch,139815.0,democrat,-22792.0,Vermont,50,VT,00,50
3329,2010,Vermont,0,Paul D. Beaudry,76403.0,republican,Peter Welch,154006.0,democrat,-77603.0,Vermont,50,VT,00,50
3330,2012,Vermont,0,Mark Donka,67543.0,republican,Peter Welch,208600.0,democrat,-141057.0,Vermont,50,VT,00,50
3331,2014,Vermont,0,Mark Donka,59432.0,republican,Peter Welch,123349.0,democrat,-63917.0,Vermont,50,VT,00,50
3332,2018,Vermont,0,Anya Tynio,70705.0,republican,Peter Welch,188547.0,democrat,-117842.0,Vermont,50,VT,00,50